Enum role_type {
  admin
  user
}

Table utilisateur {
  id int [pk, increment]
  username varchar(100)
  email varchar(150) [unique]
  password varchar(255)
  role role_type
  Note: 'Seuls les utilisateurs ayant le rôle admin peuvent créer ou importer des films'
}

Table movie {
  id int [pk, increment]
  tmdb_id int // identifiant TMDB du film
  title varchar(255)
  description text
  release_date date
  director varchar(255)
  runtime int
  poster_path varchar(255)
  backdrop_path varchar(255)
  vote_average float
  vote_count int
  id_utilisateur int [ref: > utilisateur.id]
}

Table genre {
  id int [pk]
  name varchar(100)
}

Table actor {
  id int [pk, increment]
  tmdb_id int // identifiant TMDB de l’acteur
  name varchar(255)
  original_name varchar(255)
  gender int
  biography text
  birthday date
  deathday date [note: 'Nullable']
  place_of_birth varchar(255)
  profile_path varchar(255)
  popularity float
  known_for_department varchar(255)
}

Table movie_genre {
  id_movie int [ref: > movie.id]
  id_genre int [ref: > genre.id]
  Note: 'Relation entre les films et les genres'
  Indexes {
    (id_movie, id_genre) [pk]
  }
}

Table movie_actor {
  id_movie int [ref: > movie.id]
  id_actor int [ref: > actor.id]
  character_name varchar(255)
  order_index int // ordre d’apparition
  Note: 'Relation entre les films et les acteurs'
  Indexes {
    (id_movie, id_actor) [pk]
  }
}
